### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by theaspect** [Kupchinsky/TRPO_AAA#2]
Смотрел https://github.com/Kupchinsky/TRPO_AAA/compare/v2.0...v3.0
1. Используй log4j2 стандартный джавовый логгер сто лет никто не использует
2. Логгер должен создаваться в каждом контроллере иначе в логах будет выглядеть будто только `UserController` пишет логи. Логи фильтруются оп имени класса, например, всё что логируется из `ConsoleMain` должно быть с уровенем WARN а все остальные DEBUG
3. Сам логгер инициализируй через конфиг, https://logging.apache.org/log4j/2.x/manual/configuration.html для этого положи конфиг в /src/main/resources либа увидит и подтянет https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html
4. Выясни почему так `logger.log(Level.SEVERE, "User " + e.getCauseUserName() + " not found in database!", e);` делать крайне не рекомендуется, особенно если вот этот метод `e.getCauseUserName()` был бы ресурсоёмким
5. `logger.log(Level.SEVERE` для каждого уровня есть отдельные методы, короче и понятнее
6. `if (logger != null)` если инициализируешь статик поле в каждом классе то логгер гарантированно будет не нулл.
7. Впервые вижу как логгер закрывается  

```
  + if (logger != null) {  
  +                for (Handler handler : logger.getHandlers()) {  
  +                    if (handler instanceof FileHandler)  
  +                        handler.close();  
  +                }  
  +            } 
```
1.  `public enum Role > public static String asList()`
   в каждом enum есть метод values() который делает то же самое

В остальном :+1:

**Comment by Kupchinsky** [comment]
Closed

**Comment by theaspect** [comment]
Вот тут 

https://github.com/Kupchinsky/TRPO_AAA/compare/v3.0...v3.1?diff=split&name=v3.1#diff-a2974ce6f6b588c0069289da416f3596R122

замени  `asList()` на `values()` в **следующем** релизе

Req3 готов :+1:

**Comment by Kupchinsky** [comment]
values().toString() выдаст список названий констант?

**Comment by theaspect** [comment]
toString() делается автоматически, если такой вариант тебя не устраивает, тогда согласен, оставляй метод
```
groovy:000> enum Test {READ, WRITE, EXECUTE}
groovy:000> print Test.values()
[READ, WRITE, EXECUTE]
```
